FROM maven:3.9.6-eclipse-temurin-21 AS build

WORKDIR /app
COPY . .
RUN mvn -pl audit-service -am clean package -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app
COPY --from=build /app/audit-service/target/audit-service-1.0.0.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
