# version: "3.9"

services:

  elasticsearch:
    image: elasticsearch:8.15.0
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - microservices-net

  logstash:
    image: logstash:8.15.0
    container_name: logstash
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "5044:5044"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    networks:
      - microservices-net

  kibana:
    image: kibana:8.15.0
    container_name: kibana
    restart: unless-stopped
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - microservices-net

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: api-gateway

    ports:
      - "8082:8082"
    depends_on:
      discovery-server:
        condition: service_healthy

    environment:
      SPRING_APPLICATION_NAME: api-gateway
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      JWT_PUBLIC_KEY: /run/secrets/jwt_public_key

      # REQUIRED FOR LOGGING STARTER
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5000

    volumes:
      - ./secrets/jwt_public_key.pem:/run/secrets/jwt_public_key:ro

    networks:
      - microservices-net


  discovery-server:
    build:
      context: .
      dockerfile: Dockerfile.discovery
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      SPRING_APPLICATION_NAME: discovery-server
      SPRING_PROFILES_ACTIVE: docker

      # REQUIRED FOR LOGGING STARTER
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5000

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - microservices-net

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.auth
    container_name: auth-service
    ports:
      - "9090:9090"
    depends_on:
      discovery-server:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: auth-service
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      # REQUIRED FOR LOGGING STARTER
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5000

    volumes:
      - ./secrets/jwt_private_key.pem:/run/secrets/jwt_private_key
      - ./secrets/jwt_public_key.pem:/run/secrets/jwt_public_key

    networks:
      - microservices-net

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reactive_auth_db
    ports:
      - "3307:3306"   # FIXED: expose MySQL on 3307 instead of 3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - microservices-net

  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  mysql_data:
  elasticsearch_data:
